name: Schedule post

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  schedule:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: jannekem/publish-schedule-action@v1.2
      with:
        interval: 60
        content_directory: content
      id: publish
    - name: Trigger build
      if: steps.publish.outputs.is_scheduled == 'true'
      run: curl -X POST -d {} $NETLIFY_BUILD_HOOK
      env:
        NETLIFY_BUILD_HOOK: ${{ secrets.NETLIFY_BUILD_HOOK }}